# Generated by Django 5.0.3 on 2024-07-14 06:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
