# Generated by Django 5.0.3 on 2024-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=4000),
        ),
    ]
